config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'
  
  
  resources :users, only: [:show, :edit, :update, :index]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  get 'home/about', to: 'home#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys =>[:name]
         
         validates :name, presence: true, uniqueness: true ,length: { in: 2..20 }
         validates :email, presence: true, uniqueness: true, length: { maximum: 50 }
         validates :introduction, length: { maximum: 50 }
         
         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :favorited_books, through: :favorites, source: :book
         has_many :book_comments
         
         has_one_attached :profile_image
         
#         def get_profile_image
#     unless profile_image.attached?
#       file_path = Rails.root.join('app/assets/images/no_image.jpg')
#       profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
#     end
#     profile_image.variant(resize_to_limit: [100, 100]).processed
#   end
         
#          def email_required?
#           false
#          end
         
#          def email_changed?
#           false
#         end
        
        
        def get_profile_image(width, height)
            unless profile_image.attached?
              file_path = Rails.root.join('app/assets/images/no_image.jpg')
              profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
            end
            profile_image.variant(resize_to_limit: [width, height]).processed
          end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index, :about]
     before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user)
  end

def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
  
  


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to book_path(@book)
    else
      redirect_to book_path(@book)
    end
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @comment.destroy
    redirect_to book_path(@comment.book)
end

  private

  def comment_params
    params.require(:book_comment).permit(:comment)
  end

  def correct_user
      @comment=BookComment.find(params[:id])
     unless @comment.user == current_user
      redirect_to book_path(@comment.book)
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    before_action :correct_user, only: [:edit, :update]

    def index
        @books=Book.all
        @user=current_user
        @book=Book.new
    end
    
    def show
      @book1 = Book.find(params[:id])
      @book = Book.new
      @user = @book1.user
      @comment=BookComment.new
    end
    
    def new
    @book = Book.new
    flash[:notice] = "You have created book successfully."
    end

def edit
  set_book
  flash[:notice] = "You have updated book successfully."
  end

  # POST /books
  def create
    @book = current_user.books.build(book_params)

    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books=Book.all
      @user=current_user
      render :index
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
   
    def set_book
      @book = Book.find(params[:id])
    end

  def correct_user
    unless @book.user == current_user
      redirect_to books_path
      end
    end
    
    def book_params
      params.require(:book).permit(:title, :body, :author, :description, :published_at)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    current_user.favorites.create(book: book)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book: book)
    favorite.destroy if favorite
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
 before_action :correct_user, only: [:edit, :update]
  
  def index
    @users=User.all
    @user=current_user
    @book=Book.new
  end

  def show
    @user=User.find(params[:id])
    @book = Book.new
    @books=@user.books
  end

  def edit
  end
  

  def update
    @user=set_user
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end
  
  private
  
  def correct_user
    unless @user == current_user
      redirect_to user_path(current_user)
      end
end
  
   def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h1>New book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
  
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Opinion %>
    <br>
    <%= form.text_area :body %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', book_path(@book) %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-3 ">
    <%= render 'devise/shared/user_info', user: @user %>
    <%= render 'books/form', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Profile Image</th>
          <th>Title</th>
          <th>Body</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <% if book.user.profile_image.attached? %>
                <%= link_to(image_tag(book.user.profile_image, size: "50x50"), user_path(book.user)) %>
              <% else %>
                <%= link_to(image_tag('no_image.png', size: "50x50"), user_path(book.user)) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
                <% if current_user.favorites.exists?(book: book) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fa fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
               <% end %> 
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>
           </tr>
       
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/books/new.html.erb
<%= render 'books/form', book: @book %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container">
<div class="row">
     <div class="col-md-3 ">
        <%= render 'devise/shared/user_info', user: @user %>
        <%= render 'books/form', book: @book %>
      </div>


<div class="col-md-8 offset-md-1">
    <h1>Book detail</h1>
    <table class="table">
      <thead>
        <tr>
        </tr>
      </thead>
      <tbody>
          <tr>
          <td>
            <% if @book1.user.profile_image.attached? %>
              <%= image_tag @book1.user.profile_image, size: "50x50", class: "img-thumbnail" %>
            <% else %>
              <%= image_tag 'no_image.png', size: "50x50", class: "img-thumbnail" %>
            <% end %>
              <p><%= link_to @book1.user.name, user_path(@book1.user) %></p>
          </td>
          <td><%= link_to @book1.title, book_path(@book1), class: "text-decoration-none" %></td>
          <td><%= @book1.body %></td>
          <% if current_user == @book1.user %>
          <td>
              <%= link_to 'Edit', edit_book_path(@book1), class: "btn btn-success btn-sm", id: "edit-book-link" %>
              </td>
              <td>
              <%= link_to 'Destroy', @book1, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
            
          </td>
          <% end %>
          <td> 
                <% if current_user.favorites.exists?(book: @book1) %>
                  <%= link_to book_favorites_path(@book1), method: :delete do %>
                    <i class="fa fa-heart"></i> <%= @book1.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book1), method: :post do %>
                    <i class="fa fa-heart"></i> <%= @book1.favorites.count %>
                  <% end %>
                <% end %>
             </td>
             <td>
               <p>コメント数: <%= @book1.book_comments.count %></p>
             </td>
        </tr>
      </tbody>
    </table>
    
      <h3>コメント一覧</h3>
      <% @book1.book_comments.each do |comment| %>
        <div class="comment">
          <%= image_tag comment.user.get_profile_image(100,100) %>
          <p><%= comment.comment %></p>
          <p>投稿者: <%= link_to comment.user.name, comment.user %></p>
          <% if comment.user == current_user %>
            <%= link_to 'Destroy', book_book_comment_path(@book1, comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
          <% end %>
        </div>
      <% end %>
      
      
      <%= form_with model: [@book1, @comment] do |form| %>
    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment %>
    </div>
    <div class="actions">
      <%= form.submit '送信' %>
    </div>
  <% end %>
      
  </div>
</div>
</div>

app/views/home/about.html.erb
<div class="all">
 <div class="col-md-6 mx-auto ">
<h1>welcome to  <i class="fas fa-book"></i> Bookers !!</h1>

app/views/home/index.html.erb
<%= flash[:notice] %>
<div class="all">
 <div class="col-md-6 mx-auto ">
<h1>welcome to  <i class="fas fa-book"></i> Bookers !!</h1>


<p>In <i class="fas fa-book"></i>Bookers,</p>
<br>
<p>you can share and exchange your opinions, inpressions, and emotions</p>
<p>about various books !</p>

<div class="col-10 mx-auto">
  <%= link_to 'Log in', new_user_session_path, class: 'btn btn-info' %>
  <br>
 <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success' %>
 </div>
 
 </div>
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/91b73b2073.js" crossorigin="anonymous"></script>

    <style>

    .navbar ul {
      list-style-type: none ;
      padding-left: 0 ; 
      margin-left: auto ; 
      display: flex; 
      justify-content: flex-end ; 
    }
  </style>
</head>

<body>
    <header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Bookers", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link" do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
               <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

  </header>

  <%= yield %>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/users/edit.html.erb
<h1>User Info</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
   <div class="field">
    <%= form.label :profile_image %>
    <%= form.file_field :profile_image %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="actions">
    <%= form.submit 'Update User' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="col-md-3">
    <%= render 'devise/shared/user_info', user: @user %>
    <%= render 'books/form', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h1>Users</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image, size: "50x50" %>
              <% else %>
                <%= image_tag 'no_image.png', size: "50x50" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'devise/shared/user_info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if book.user.profile_image.attached? %>
                  <%= link_to(image_tag(book.user.profile_image, size: "50x50"), user_path(book.user)) %>
                <% else %>
                  <%= link_to(image_tag('no_image.png', size: "50x50"), user_path(book.user)) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book %></td>
              <td><%= book.body %></td>
              <td>
                <% if current_user.favorites.exists?(book: book) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fa fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>